services:
    mysql:
        image: mysql:8.4.0
        container_name: coffee-machine.mysql
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_ROOT_PASSWORD: 'coffee_machine'
            MYSQL_DATABASE: 'coffee_machine'
            MYSQL_USER: 'coffee_machine'
            MYSQL_PASSWORD: 'coffee_machine'
        ports:
            - "3305:3306"
        volumes:
            - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
        tty: true

networks:
    default:
        name: coffee-machine_net
        external: true
